### ISSUE TITLE
inheritSlots tag?

### ISSUE THREAD

**Issue by imanuelcostigan** [klutometis/roxygen#145]
Would be nice to have an inheritSlots tag that operates similarly to the inheritParams tag. 

Namely, if class A is a superclass of class B, and class B has additional slots (say `slot1` and `slot2`) to class A, then slots should be documented along the lines of the following

```
@inheritSlots classA
@slot slot1
@slot slot2
```

Cheers

**Comment by Geoff99** [comment]
Did anything come of this idea - is it still on the todo list or is it too complex?

I ask because I have just reached the stage in my own package (which I am building as a learning exercise for me), where something like this would be really useful.  `devtools::check()` is detecting (quite correctly) `S4 class codoc mismatches from documentation object` because I haven't done a good job of documenting inherited slots.  

Admittedly, my inherited slots come from external packages, so I would be interested in the general `@inheritSlots pkg::class ` case and I really understand why that would be difficult and messy. 

In my case though I would be happy enough if the `@inheritSlots pkg::class` just found the names of the slots that were being inherited (which I *believe* (he said innocently and blithely) could be found from the loaded code, without needing to parse the `pkg` rds file).  Given the inherited slot names it might be possible to construct something akin to what would happen if I typed in manually:

```
#' @slot inheritedslot1 see "?pkg::class" for details   
#' @slot inheritedslot2 see "?pkg::class" for details, etc
```

It's not perfect, but it would get me "out of jail" and provide a template which I could improve by hand.

Quite understand if this would fall into the negative 80/20 rule (80% of effort for only 20% of benefit).
