### ISSUE TITLE
compile doxygen if src directory exists 

### ISSUE THREAD

**Issue by dlebauer** [klutometis/roxygen#326]
add 'doxygen' as a new roclet. 
- check if `src/` directory exists
  - if true, check if `Doxyfile` exists 
  - if false, create one
- run `system("doxygen path/to/Doxyfile")`

The code is available in pull request to hadley/devtools#724 and in the answer to [related question on StackOverflow](http://stackoverflow.com/a/28678741/513006) (both by @cbarbu)

his code puts the documentation in `inst/doxygen`

**Comment by hadley** [comment]
Do you want to prepare a PR? I'd be happy to review.

**Comment by dlebauer** [comment]
@cbarbu do you want to move your PR hadley/devtools#724 here?

**Comment by cbarbu** [comment]
@dlebauer Sure I'm trying to figure out how to do it.

**Comment by dlebauer** [comment]
Followed up by #387 and then #398

**Comment by hadley** [comment]
I think this should go in its own package - I'm not a big fan of doxygen, and now all the tooling exists in roxygen2 so that you can define roclets in other packages.

**Comment by mlysy** [comment]
@hadley may I ask what you suggest instead of doxygen for documenting C++ (and especially R package `src`) code?

Perhaps you would agree with my opinion that C++ code R packages is too often poorly documented, and often as a result also ill-designed and inefficient.  I believe that R-oriented `src` documentation tools would motivate many package developers to produce better source code.

With this in mind, @nevrome and I have created the [rdoxygen](https://github.com/mlysy/rdoxygen) package.  This is essentially an R interface to doxygen with the ability to wrap the doxydoc as an R package vignette.

In my opinion, the major issue we are facing is that doxygen documentation is rather large -- the upfront cost is ~300Kb (though the incremental cost per line of source documentation is small).  In many cases this exceeds the size of the rest of the package, which is not very appealing given CRAN's request to use space economically.

So, we are very open to any suggestions you might have on how R package developers should document their C++ code.

**Comment by hadley** [comment]
I don't have a suggestion. I _really_ don't like doxygen documentation. My experience with it as a reader of C++ documentation has been almost universally negative, and in most cases I find that it's easier to just read the source code than attempt to understand the generated docs. That's not to say that you shouldn't use it, just that you shouldn't expect me to be excited about it.

**Comment by gaborcsardi** [comment]
@hadley I largely had the same experience. For igraph we wrote our own system based on gtk-doc (https://www.gtk.org/gtk-doc/), which has a syntax similar to Doxygen, but can make use of templates, to order and group the classes and functions nicely, not unlike a pkgdown reference page. The result looks like this: https://developer.gnome.org/glib/stable/
https://developer.gnome.org/glib/stable/glib-Memory-Allocation.html

gtk-doc uses Docbook and XML, which is not particularly great, though. I am also not sure how well it supports C++, gtk being written in C. There are probably other tools that are more modern, Python must have sg for their C API.

I agree that it is probably possible to write a roclet that creates nice R man pages from doxygen-like comments.

**Comment by mlysy** [comment]
@hadley and @gaborcsardi thank you very much for your feedback.  I think that doxygen code markup is perhaps simplest from a developer's perspective, so the issue is converting this to some sort of output.  In this respect, I think that most developers would love to have an easy way to control the look & feel of things.  So I guess it would be nice extract the doxydoc into R objects that could be inserted into an Rmd template...

I looked into this at some point and parsing the doxygen xml output is just barrels of fun.  [breathe](https://breathe.readthedocs.io/en/latest/) and [moxygen](https://www.npmjs.com/package/moxygen) do this in Python and JavaScript, respectively, but I don't know either well enough that porting to R wouldn't be easier than starting from scratch...
