### ISSUE TITLE
@describeIn is ignored in this example

### ISSUE THREAD

**Issue by gustavdelius** [klutometis/roxygen#356]
The following code correctly leads to two Rd files, named classdemo-class for the class description and classdemo for the description of the generic constructor. However, the descriptions of the methods show up in the classdemo-class file rather than in the classdemo file, in spite of the explicit @describeIn tags.
```
#' A demo class
setClass("classdemo")

#' Generic constructor
#' 
#' @param x Initial value
setGeneric('classdemo', function(x) standardGeneric('classdemo'))

#' @describeIn classdemo Construct demo with numeric argument
setMethod('classdemo', signature(x='numeric'), function(x) new("classdemo"))

#' @describeIn classdemo Construct demo with character argument
setMethod('classdemo', signature(x='character'), function(x) new("classdemo"))
```

**Comment by hadley** [comment]
The problem is that the class and generic both have the same name, and roxygen2 looks first for the class. It seems like a rather unusual design to have both generic and class with the same names, so it's not high-enough priority for me to fix.  

However, if you wanted to fix it, you could submit a pull request. I'd recommend allowing an additional suffix to disambiguate classes from other objects, e.g. `@describeIn classdemo-class`. You'd then need to modify find object to detect that suffix and add a few unit tests.
