### ISSUE TITLE
extra RD files generated

### ISSUE THREAD

**Issue by winnieyeung115** [klutometis/roxygen#454]
Hi,

I am trying the build and check my package using roxygen2 version 5.0.1 in Rstudio. When I check my package, there are some extra Rd files generated (they should not be generated as there are no related documentation in my package) and giving an error message for my check. 
I also tried to use roxygen2 version 4.1.1 to build and check my package. These extra RD files were not generated and I have no errors after the check. The extra Rd files are only generated when I use roxygen2 version 5 or above. I also checked my package with win-builder and I obtained no error.

I was wondering why the extra Rd files are generated. Any advice would be very appreciated.

**Comment by danielinteractive** [comment]
I can confirm this problem.
More specifically, the error message is "Sections \title, and \name must exist and be unique in Rd files". When I check the generated man files there is one file relating to the S4 generic function and another file relating to the S4 method. The man file for the S4 method should not have been produced (and is not produced by version 4.1.1 of roxygen2), because I used the @describeIn above the corresponding setMethod(...) statement.
Could you please help?

**Comment by hadley** [comment]
You probably have a bad `@rdname`. You get a better warning in the dev version
