### ISSUE TITLE
inter-package \link format

### ISSUE THREAD

**Issue by jeroenooms** [klutometis/roxygen#534]
Is there a markdown equivalent for inter-package links:

``` tex
\link[openssl:signature_verify]{signatures}
```

Perhaps we can recognize `foo:bar` hyperlinks as package links? 

``` md
You can use digital [signatures](openssl:signature_verify) to verify integrity.
```

**Comment by hadley** [comment]
You mean `foo::bar`, right?

**Comment by jeroenooms** [comment]
No, if you want to make a named `\link` to another package you need a single colon.

**Comment by hadley** [comment]
I think It would be weird to mimic that syntax in markdown, instead of using the standard `foo::bar` (which I feel like @gaborcsardi already added)

**Comment by jeroenooms** [comment]
Hmm I don't think that works currently. I tried with a link like this:

```
plus custom SSH [pubkey](openssl::read_key) parsers
```

But that turns into

```
plus custom SSH \href{openssl::read_key}{pubkey} parsers
```

What I need is something that turns into

plus custom SSH \link[openssl:read_key]{pubkey} parsers
`

**Comment by gaborcsardi** [comment]
@jeroenooms 

> No, if you want to make a named \link to another package you need a single colon.

So you want and *inter*package link then, right?

You can do it like this (note the brackets):
```
[signatures][openssl::signature_verify]
```
Is this what you want?

More here:
https://github.com/klutometis/roxygen/blob/master/vignettes/markdown.md#links

**Comment by gaborcsardi** [comment]
@jeroenooms Does this fix your problem?

**Comment by jeroenooms** [comment]
Yes this is what I wanted, thanks. What is the rationale for requiring brackats instead of parentheses here? Would there be any ambiguity of supporting `[signatures](openssl::signature_verify)`

**Comment by gaborcsardi** [comment]
`[][]` generates `\link{}` links, `[]()` generates `\href{}` links.

**Comment by gaborcsardi** [comment]
To elaborate more, it seemed like a good idea to leave the mechanism for external links untouched. (Because the `[]` and `[][]` links are handled via a number of hacks.)

In theory, we could also allow `[]()` links to generate `\link{}` links, but then we would need to parse the contents and decide if we want to generate a `\href{}` (or `\url{}`) or a `\link{}` (or `\code{\link{}}`) for them. Although most `[]()` links are either `link{}` links or `http` or `https` I suppose, I didn't want to make assumptions, and just went with the distinction between `\href{}` and `\link{}` links. The former is `[][]` and the latter is `[]()`. This is simple, and I don't think we lose much.

**Comment by gaborcsardi** [comment]
@jeroenooms Can we close this? Assuming you can live without `[]()` R links....

**Comment by jeroenooms** [comment]
Yes sorry :)
