### ISSUE TITLE
roxygenise is deleting trailing newlines

### ISSUE THREAD

**Issue by philmikejones** [klutometis/roxygen#593]
When I run `roxygen2::reoxygenise()` with `devtools::document()` on my documentation the trailing newline at the end of the file is being stripped.
I've seen [this issue](https://github.com/klutometis/roxygen/pull/543) but instead of removing _extra_ newlines, it's also deleting the one trailing newline at the end.

`roxygen2` version 6.0.1; `devtools` version 1.12.0

Any suggestions?
Thanks.

**Comment by hadley** [comment]
Can you please provide a minimal reprex (reproducible example)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please [help me help you](https://nypdecider.files.wordpress.com/2014/08/help-me-help-you.gif)! 

If you've never heard of a reprex before, start by reading "[What is a reprex](http://reprex.tidyverse.org/articles/reprex.html)", and follow the advice further down the page. Please make sure your reprex is created with the reprex package as it gives nicely formatted output and avoids a number of common pitfalls.

**Comment by philmikejones** [comment]
Thanks Hadley. Will do next time it happens.
