### ISSUE TITLE
Line break in Markdown link text deletes whitespace between words

### ISSUE THREAD

**Issue by jennybc** [klutometis/roxygen#628]
If line wrapping causes a line break in the text of a Markdown link, the associated space between words goes missing. This does not happen with Rd syntax.

Example of the roxygen comment:

```r
#' Generate a request for the Sheets v4 API
#'
#' Generate a request, using some knowledge of the [Sheets v4
#' API](https://developers.google.com/sheets/api/reference/rest/). Blah blah
#' \href{https://developers.google.com/sheets/api/reference/rest/}{Sheets v4
#' API} Most users should, instead, use higher-level wrappers that facilitate
#' common tasks, such as reading the contents of a sheet. The functions here are
#' intended for internal use and for programming around the Sheets API.
```

Screenshot of the help. Note "Sheets v4API" (no space, from Markdown) versus "Sheets v4 API" (with space, from Rd), despite a line break falling in exactly the same place.

<img width="633" alt="screen shot 2017-05-09 at 3 01 13 pm" src="https://cloud.githubusercontent.com/assets/599454/25874672/6c72d68c-34c8-11e7-9100-4c9a7ad6672e.png">

**Comment by egnha** [comment]
Here's a somewhat shorter demonstration of the problem:
```R
out <- roc_proc_text(rd_roclet(), "
  #' Title
  #'
  #' Link text [broken
  #' across lines](url) doesn't preserve whitespace.
  #' @md
  foo <- function() {}")[[1]]
```
gives
```
% Generated by roxygen2: do not edit by hand
% Please edit documentation in Rtmpp2fxtt/fileb6077549a9
\name{foo}
\alias{foo}
\title{Title}
\usage{
foo()
}
\description{
Link text \href{url}{brokenacross lines} doesn't preserve
whitespace.
}
```

**Comment by egnha** [comment]
Unwinding the (internal) function `markdown()`, it looks like the culprit is the call `xml_text(xml)` in the `link` method in [`markdown_tags`](https://github.com/klutometis/roxygen/blob/master/R/markdown.R#L185):
```R
invisible(markdown_on(TRUE))
markdown("[broken\nacross lines](URL)", markdown_tags)
#> [1] "\\href{URL}{brokenacross lines}"
```
It seems that the newline isn't preserved as whitespace because when `markdown()` produces the final link text by calling
```R
xml_text(xml)
```
on the XML object
```R
```
"
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE document SYSTEM "CommonMark.dtd">
<document xmlns="http://commonmark.org/xml/1.0">
  <paragraph>
    <link destination="URL" title="">
      <text>broken</text>
      <softbreak />
      <text>across lines</text>
    </link>
  </paragraph>
</document>
"
 <- xml2::read_xml(xml)
(markdown_tags$paragraph(markdown_tags$document(x)[[1]])[[2]])
```
```R
markdown("[broken\nacross lines](URL)", markdown_tags)
[1] "\\href{URL}{broken across lines}"
```
