### ISSUE TITLE
@inherit Doesn't inherit description if not inheriting title

### ISSUE THREAD

**Issue by ssokolen** [klutometis/roxygen#629]
This might be a feature rather than a bug, but the following doesn't seem to work as expected. Unless I include `@inherit title`, `@inherit description` doesn't work. 

Original function:
```
#' This is title
#' 
#' This is description
#'
#' @param x x
#' @param y y
#'
#' @return numeric vector
f1 <- function(x, y) x + y
```
Function that will inherit f1:

```
#' Different title
#'
#' @inherit f1 description 
#'
#' @inheritParams f1
#' @param z z
#'
#' @inherit f1 return
f2 <-function(x, y, z) x + y + z
```
This results in `\description{}` of f2 to be: "Different title". If I modify the title to `@inherit f1 title`, the `\description{}` of f2 is correctly inherited as "This is description"

**Comment by hadley** [comment]
Minimal reprex:

```R
out <- roc_proc_text(rd_roclet(), "
  #' T1
  #' 
  #' D1
  f1 <- function() 1
  
  #' T2
  #' @inherit f1 description 
  f2 <-function() 2
")

out[[1]]$get_field("description")$values
out[[2]]$get_field("description")$values
```

**Comment by hadley** [comment]
It happens because the repetition of title into description happens when the block is parsed. That means the inheritance code sees that a description already exists and skips the inheritance. To fix this, we'll need to move the insertion of the default description much later in the process - presumably just before the Rd file is written.
