### ISSUE TITLE
Add custom header/comment to Rd files?

### ISSUE THREAD

**Issue by leepface** [klutometis/roxygen#817]
Is it possible to add a custom header/comment to Rd files below the current one? We have:

```
% Generated by roxygen2: do not edit by hand
% Please edit documentation in R/function.R
```

And want to be able to add a copyright notice below that:

```
% Generated by roxygen2: do not edit by hand
% Please edit documentation in R/function.R
% Copyright blah blah blah
```

But as far as I can tell there's no tag that adds a comment to the Rd file *outside of* a section. Maybe there's another fix?

**Comment by hadley** [comment]
There's no way to do so currently. I'd consider a PR for it, but I have no idea where you would specify the comment, so it's likely to require quite some thought.

**Comment by mschilli87** [comment]
@hadley: I hope it is OK to re-open this old issue rather than opening a new one and linking to this one.

I have the same issue with the specific aim of properly indication the license. IANAL but AFAIC, a file (in this case: an `*.Rd` file) auto-generated (in this case by `roxygen2`) from a source file (in this case: the corresponding `*.R` file) licensed under the GPL, it IMHO qualifies as a 'derivative work' and thus must by licensed under the GPL as well. Thus, I'd like to copy the copyright and licensing information from the source file to the generated one.

An ideal solution for me would be `roxygen2` to actually 'understand' this entire process and generate the appropriate header automatically, keeping it up to date (*i.e.* adding new copyright lines for new authors, updating the copyright year, etc.). However, this is probably asking too much and I certainly wouldn't have the time to put together a PR myself.
A workable solution for me would be for roxygen to simply scan any existing file for the '*Generated by roxygen2: do not edit by hand*' line and copy anything *above* it verbatim to the generated file. AFAICT this approach would be i) backwards compatible (as existing files start with the `roxygen2` note), and ii) easy to implement (I'd be willing to provide a PR if it has a chance of actually getting merged) and maintain.

@hadley: Any feedback back regarding your thoughts on this would be highly appreciated.

@leepface: Would the solution suggest by me solve for your use case as well? Did you find any other (better?) solution/workaround to this problem?

**Comment by hadley** [comment]
@mschilli87 please file a new issue and don’t at me unless it’s urgent.
